{{- if and .Values.ingress.enabled (eq .Values.ingress.standalone true) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "azure-application-gateway" }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "azure-application-gateway" }}
  rules:
    - http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "backend.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
{{- end }}